### ISSUE TITLE
an improved favicon.ico?

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BioC2019#14]
Would be great to have an updated favicon.ico (the icon that appears in the browser tab). Currently it's https://bioc2019.bioconductor.org/images/favicon.ico ; a nicer alternative might do something with the bioc 'note' that occurs in all the logos, e.g., https://bioconductor.org/images/logo_bioconductor.gif . @jotsetung ?

**Comment by jorainer** [comment]
Agree. I guess the full note (including the DNS-dots) would be nice. The limitation to 16x16 pixels might be challending though. Alternatively just use BC (for BioConductor), B colored with the Bioconductor-blue, C with the Bioconductor-green.

**Comment by nsheff** [comment]
at some point I made or scrounged an SVG that could be used/adapted for this: 

http://databio.org/images/logo/bioconductor.svg

it's just black and white, though.

**Comment by mtmorgan** [comment]
I'm not sure what happens to it at 16 x 16 pixels?

**Comment by LiNk-NY** [comment]
This happens with:
```
convert ~/Pictures/bioconductor.svg -resize 16x16 biocon.png
```
![biocico](https://user-images.githubusercontent.com/4392950/53121743-e0e86e80-3522-11e9-8d19-ea71bd8bc25d.png)

**Comment by nsheff** [comment]
here's a direct inkscape export with transparent background:

![bioconductor](https://user-images.githubusercontent.com/5271009/53123815-f01deb00-3527-11e9-9451-3c184afe7703.png)
