### ISSUE TITLE
404s from 7 sidebar links on Firefox 64.0.2

### ISSUE THREAD

**Issue by omsai** [Bioconductor/BioC2019#15]
I was trying to visit the travel and accommodation link during today's conference call but on Firefox 64.0.2 clicking on the left side bar I get 404 for several links:

1. Conference Home - https://bioc2019.bioconductor.org/index/
2. Registration - https://bioc2019.bioconductor.org/registration/
3. Travel & accomodation https://bioc2019.bioconductor.org/travel-accommodations/
4. Main conference - https://bioc2019.bioconductor.org/schedule/
5. Robert Gentleman day - https://bioc2019.bioconductor.org/schedule-gentleman-day/
6. Organizing committee - https://bioc2019.bioconductor.org/organizers/
7. Code of conduct - https://bioc2019.bioconductor.org/code_of_conduct/

Perhaps GitHub did not render the website properly on the latest push?  Is there some way to manually trigger a rebuild of gh-pages like there is on GitLab?

Interestingly, the working links don't have a trailing slash, and all the failing links have trailing slashes.  But removing the trailing slash doesn't help.  Which makes me wonder if there is some sort of Jekyll redirection issue.  Probably best to reproduce locally and `git bisect` to find when this issue came up.

**Comment by mtmorgan** [comment]
I don't see this on chrome or safari; what does 'view source' show as the link (trailing slash or no?)

**Comment by omsai** [comment]
I see GitHub's 404 page:

![screenshot_2019-03-05_10-59-16](https://user-images.githubusercontent.com/166624/53818396-00759300-3f36-11e9-95e0-548a2fdaf2d0.png)

Some more information which reduces the severity:

1. I cannot reproduce the problem using the same browser with the local Jeykll instance.
2. I cannot reproduce the problem using my laptop's Firefox 60.1.0esr.

I'll try my web search-fu looking for bugs related to version 64.0.2 of Firefox with Jekyll, etc.

**Comment by omsai** [comment]
Ok I'm not sure what's changed, but it's working now on 64.0.2.  Maybe it was an issue with GitHub's CDN or something.

Damn Heisenbugs!
