### ISSUE TITLE
website update: names for presenters

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BioC2019#27]
Add names to developer day and main conference workshops. Suggest format `Title -- Person(s)` with title first to emphasize content rather than presenter.

**Comment by lpantano** [comment]
there are some workshops with many authors, like more than 10, should I put all?

**Comment by mtmorgan** [comment]
Since they'll be listed in full in the workshop, I suggest only a max of 3(???)

**Comment by mtmorgan** [comment]
closed by #31
