### ISSUE TITLE
website: gentleman day confirmed attendees

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BioC2019#29]
Not sure @wolfganghuber (?) about this section; there are currently >120 people indicating that they'll attend...

**Comment by wolfganghuber** [comment]
Which section do you mean Martin? http://bioc2019.bioconductor.org/schedule-gentleman-day -> Confirmed attendees ? We can drop it.

**Comment by mtmorgan** [comment]
https://github.com/Bioconductor/BioC2019/blame/master/docs/schedule-gentleman-day.md#L70-L84
