### ISSUE TITLE
SIG: Projects at the intersection of data / tech and longevity

### ISSUE THREAD

**Issue by ghost** [Bioconductor/BioC2019#32]
Introduction: From Physics / Math to Data Scientist (in EdTech and CivicTech) to data & longevity. Bringing over a decade of data experience to one of my deepest yearnings: for humankind to have an option to live longer and healthier. 

We are capable of so much, technologically, culturally, and personally, and in that spirit, I have started an initiative titled [MoreLife](https://www.morelife.tech). [See [Data / tech for longevity](https://www.meetup.com/Data-Tech-for-longevity/) meetup in NYC.]

Description: Discuss and code for one of the two MoreLife projects: 

1. Secure collection and storing of biomarkers (test results of volunteers). The LongeCity biomarker testing database is one of the few open testing initiatives to measure the biological age and track the rejuvenation/anti-aging practices of the participants. The biomarker testing initiative just completed its first year and will test the same cohort for a second year with plans to keep the testing going on an annual basis, while also adding participants. Goal is to create an application for participants to easily enter data, such as test results, supplement regimens, and other rejuvenation efforts (like diet, fasting, exercise, meditation, etc...)
2. Database creation (for Albert Einstein​ Institute for Aging Research). The plan is development and input information of animal colony records and link them to the data generated from each mouse model. [Side Note: This project can be extended to other labs, therefore is not limited to this lab.]

The other MoreLife projects are here: [https://www.morelife.tech/projects](https://www.morelife.tech/projects), so the one best suited for this conference can be chosen.

**Comment by ghost** [comment]
A general project: standardize data collaboration between different entitites. If we wanted to bring the open data revolution to longevity, what would it take? How do we encourage researchers to open data they have already used so citizens can then analyze it and build other interesting things using it?

**Comment by mtmorgan** [comment]
Closing as off-topic.
